
FROM python:3.7

RUN pip3 install pandas setuptools pytz python-utils statsmodels patsy joblib scikit-learn==0.22 numpy pyod scipy xgboost shap tslearn neuralprophet tensorflow
ENV PYTHONUNBUFFERED=TRUE

ENTRYPOINT ["python3"]